### ISSUE TITLE
problem with sw_2.png not showing

### ISSUE THREAD

**Issue by dc34** [OdinsHat/tyre-label-generator#3]
Hi, Thank you so much for this script, it is just what I was searching for but one tiny problem. Whatever I have tried it shows sw_2.png as not showing and a tiny cross
The directory is correct but for some reason just wont render correctly. Any advice would be most welcome thanks

**Comment by OdinsHat** [comment]
As mentioned in the previous comment I've asked the designer for the original PSD to create new images from. If you went ahead and created your own I'd appreciate it if you could send it to me. doug dot bromley at gmail dot com

**Comment by OdinsHat** [comment]
sw_2 seems to be showing in the latest versiopn. So I'm closing this as fixed.
