### ISSUE TITLE
Release tag

### ISSUE THREAD

**Issue by davidromani** [OdinsHat/tyre-label-generator#5]
Hi.

It is possible to tag some commit as a release version? There are some code quality inspectors (like SensioLabsInsight) that don't like general composer.json config.  

Thx.

**Comment by OdinsHat** [comment]
Sorry for the extended wait. I honestly didn't think anyone would be using this library. I've created a v1.0 tag for you so feel free to use as you see fit. I'll be updating this library in the near future to take advantage of the latest web optimised images.

**Comment by OdinsHat** [comment]
Done.

**Comment by davidromani** [comment]
Thank you @OdinsHat ! We will wait to see upcoming changes soon 😅
